### PR TITLE
Fix the example return value for the hosts() method

### PR DESCRIPTION
**Pull request by Eronarn**
This is how you get host IDs, which are used in some other methods, so it's good to document that.

### CODE REVIEW

**Comment by Eronarn** [comment]
Also, minor weirdness: you use a host ID to get instrumentation versions, but the function documentation demonstrates passing in a string. It does accept a string, but only if it's a string of the host ID, and that actually gets returned as an int value in the dict by the corresponding method. In contrast, if you provide a string hostname, the client dies.

Not sure where to take that one!

**Comment by danriti** [comment]
@Eronarn, do you have a code example that reproduces the problem you described in the above comment?

**Comment by danriti** [comment]
@Eronarn otherwise the documentation change looks good, thanks for catching this!

**Comment by danriti** [comment]
new docs were generated: http://python-traceview.readthedocs.org/en/latest/#traceview.TraceView.hosts

(make sure to clear your cache)

**Pull request merged**
